-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TYPE "public"."agama" AS ENUM('Islam', 'Kristen', 'Katolik', 'Hindu', 'Budha', 'Konghucu');--> statement-breakpoint
CREATE TYPE "public"."jenis_kelamin" AS ENUM('Laki-Laki', 'Perempuan');--> statement-breakpoint
CREATE TYPE "public"."role" AS ENUM('Admin', 'Guru', 'Siswa', 'Tata Usaha');--> statement-breakpoint
CREATE TYPE "public"."tipe_penugasan" AS ENUM('Ujian', 'Materi', 'Tugas');--> statement-breakpoint
CREATE TABLE "tb_account" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tb_account_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"nomor_induk" text NOT NULL,
	"password" text NOT NULL,
	"role" "role" NOT NULL,
	"aktif" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"updated_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	CONSTRAINT "tb_account_nomor_induk_key" UNIQUE("nomor_induk")
);
--> statement-breakpoint
CREATE TABLE "tb_admin" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tb_admin_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"account_id" bigint NOT NULL,
	"nama" text NOT NULL,
	"jenis_kelamin" "jenis_kelamin" NOT NULL,
	"dibuat_pada" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"diubah_pada" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	CONSTRAINT "tb_admin_account_id_key" UNIQUE("account_id")
);
--> statement-breakpoint
CREATE TABLE "tb_guru" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tb_guru_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"account_id" bigint NOT NULL,
	"nama" text NOT NULL,
	"nuptk" text NOT NULL,
	"jenis_kelamin" "jenis_kelamin" NOT NULL,
	"tempat_lahir" text NOT NULL,
	"tanggal_lahir" date NOT NULL,
	"email" text NOT NULL,
	"dibuat_pada" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"diubah_pada" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	CONSTRAINT "tb_guru_account_id_key" UNIQUE("account_id"),
	CONSTRAINT "tb_guru_email_key" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "tb_siswa" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tb_siswa_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"account_id" bigint,
	"nama" text NOT NULL,
	"nipd" text NOT NULL,
	"jenis_kelamin" "jenis_kelamin" NOT NULL,
	"nisn" text NOT NULL,
	"tempat_lahir" text NOT NULL,
	"tanggal_lahir" date NOT NULL,
	"nik" text NOT NULL,
	"agama" "agama" NOT NULL,
	"kelas" text NOT NULL,
	"dibuat_pada" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"diubah_pada" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	CONSTRAINT "tb_siswa_nipd_key" UNIQUE("nipd"),
	CONSTRAINT "tb_siswa_nisn_key" UNIQUE("nisn"),
	CONSTRAINT "tb_siswa_nik_key" UNIQUE("nik")
);
--> statement-breakpoint
CREATE TABLE "tb_classroom" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tb_classroom_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"kode" text NOT NULL,
	"nama_kelas" text NOT NULL,
	"guru_id" bigint NOT NULL,
	"deleted" boolean DEFAULT false NOT NULL,
	"mata_pelajaran" text NOT NULL,
	"kelas" text NOT NULL,
	"dibuat_pada" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"diubah_pada" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	CONSTRAINT "tb_classroom_kode_key" UNIQUE("kode")
);
--> statement-breakpoint
CREATE TABLE "tb_assignment" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tb_assignment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"classroom_id" bigint NOT NULL,
	"judul" text NOT NULL,
	"deskripsi" text,
	"batas_pengumpulan" timestamp with time zone,
	"deleted" boolean DEFAULT false NOT NULL,
	"file_urls" text[],
	"tipe_assignment" "tipe_penugasan" NOT NULL,
	"dibuat_pada" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"diubah_pada" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tb_submission" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tb_submission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"classroom_id" bigint NOT NULL,
	"siswa_id" bigint NOT NULL,
	"file_urls" text[] NOT NULL,
	"terlambat" boolean DEFAULT false NOT NULL,
	"selesai" boolean DEFAULT false NOT NULL,
	"deleted" boolean DEFAULT false NOT NULL,
	"assignment_id" bigint NOT NULL,
	"dibuat_pada" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"diubah_pada" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tb_classroom_siswa" (
	"classroom_id" bigint NOT NULL,
	"siswa_id" bigint NOT NULL,
	"deleted" boolean DEFAULT false NOT NULL,
	"dibuat_pada" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	"diubah_pada" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	CONSTRAINT "tb_classroom_siswa_pkey" PRIMARY KEY("classroom_id","siswa_id"),
	CONSTRAINT "tb_classroom_siswa_classroom_id_key" UNIQUE("classroom_id")
);
--> statement-breakpoint
ALTER TABLE "tb_admin" ADD CONSTRAINT "tb_admin_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."tb_account"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tb_guru" ADD CONSTRAINT "tb_guru_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."tb_account"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "tb_siswa" ADD CONSTRAINT "tb_siswa_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."tb_account"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tb_classroom" ADD CONSTRAINT "tb_classroom_guru_id_fkey" FOREIGN KEY ("guru_id") REFERENCES "public"."tb_guru"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tb_assignment" ADD CONSTRAINT "tb_assignment_classroom_id_fkey" FOREIGN KEY ("classroom_id") REFERENCES "public"."tb_classroom"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "tb_submission" ADD CONSTRAINT "tb_submission_assignment_id_fkey" FOREIGN KEY ("assignment_id") REFERENCES "public"."tb_assignment"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tb_submission" ADD CONSTRAINT "tb_submission_classroom_id_fkey" FOREIGN KEY ("classroom_id") REFERENCES "public"."tb_classroom"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "tb_submission" ADD CONSTRAINT "tb_submission_siswa_id_fkey" FOREIGN KEY ("siswa_id") REFERENCES "public"."tb_siswa"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "tb_classroom_siswa" ADD CONSTRAINT "tb_classroom_siswa_classroom_id_fkey" FOREIGN KEY ("classroom_id") REFERENCES "public"."tb_classroom"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "tb_classroom_siswa" ADD CONSTRAINT "tb_classroom_siswa_siswa_id_fkey" FOREIGN KEY ("siswa_id") REFERENCES "public"."tb_siswa"("id") ON DELETE cascade ON UPDATE cascade;
*/